import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create schema storage; create table storage.buckets(id text primary key,name text,public boolean);`);
await db.exec(await fs.readFile(new URL('../supabase/migrations/20261005_training.sql',import.meta.url),'utf8'));
const u='11111111-1111-4111-8111-111111111111';
await db.query('insert into auth.users values($1)',[u]);
const order=async()=> (await db.query("insert into training_orders(user_id,course_id,product_id) values($1,'kader-matrisi','prod1') returning id",[u])).rows[0].id;
const pay=(id,p='pay1',prod='prod1')=>db.query('select fulfill_training_order($1,$2,$3)',[id,p,[prod]]);
const state=async(id)=>(await db.query('select status from training_orders where id=$1',[id])).rows[0].status;
let id=await order();await assert.rejects(pay(id,'pay1','wrong'));assert.equal(await state(id),'pending');
await pay(id);await pay(id);assert.equal(await state(id),'paid');
await assert.rejects(pay(id,'different'));assert.equal(await state(id),'paid');
let second=await order();await assert.rejects(pay(second));assert.equal(await state(second),'pending');
await db.query('select revoke_training_payment($1)',['pay1']);await pay(id);assert.equal(await state(id),'revoked');
await db.query('select revoke_training_payment($1)',['pay-before']);let third=await order();await pay(third,'pay-before');assert.equal(await state(third),'revoked');
await db.exec('set role authenticated');await assert.rejects(db.query('select * from training_orders'));await assert.rejects(db.query('select * from training_lessons'));await assert.rejects(pay(id));await db.exec('reset role');
assert.equal((await db.query("select public from storage.buckets where id='training-videos'")).rows[0].public,false);
console.log('SQL checks passed: migration, product mismatch, duplicate event, payment reuse, revoke/replay, refund-before-success, client denial and private bucket.');await db.close();
